<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition duration-300 ease-out"
      enter-from-class="opacity-0 scale-95"
      enter-to-class="opacity-100 scale-100"
      leave-active-class="transition duration-200 ease-in"
      leave-from-class="opacity-100 scale-100"
      leave-to-class="opacity-0 scale-95"
    >
      <div
        v-if="show"
        class="fixed inset-0 z-[99999] flex items-center justify-center bg-black/60 px-4"
      >
        <div
          class="relative w-full max-w-lg border-2 border-black bg-[#FFF8B8] p-6 md:p-8 shadow-[10px_10px_0px_#000]"
        >
          <button
            @click="$emit('close')"
            class="absolute right-4 top-3 text-3xl font-black hover:text-[#A555EC]"
          >
            ×
          </button>

          <p
            class="mb-3 inline-block border-2 border-black bg-[#A555EC] px-3 py-1 text-xs font-black uppercase text-white rotate-[-2deg]"
          >
            Confidential
          </p>

          <h2 class="text-4xl md:text-5xl font-black mb-4">Case Briefing</h2>

          <div class="h-1 w-24 bg-black mb-5"></div>

          <p class="text-neutral-700 leading-relaxed mb-6">
            One image is real. One was generated by AI. Your job is to inspect
            the details, pick the suspicious image, and build your investigation
            score.
          </p>

          <button
            @click="$emit('close')"
            class="w-full border-2 border-black bg-black px-6 py-3 font-black uppercase text-white shadow-[4px_4px_0px_#A555EC]"
          >
            Start Investigation
          </button>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup>
defineProps({
  show: Boolean,
});

defineEmits(["close"]);
</script>
