<template>
  <main
    class="min-h-screen bg-[#FFFFD0] text-black flex items-center justify-center px-6 overflow-hidden"
  >
    <section
      class="relative w-full max-w-5xl border-2 border-black bg-[#FFF8B8] px-6 py-10 md:px-14 md:py-16 shadow-[12px_12px_0px_#000]"
    >
      <div
        class="absolute -top-5 left-8 bg-[#A555EC] text-white px-5 py-2 border-2 border-black rotate-[-3deg] font-bold uppercase"
      >
        Daily Case File
      </div>

      <div
        class="absolute top-8 right-8 hidden md:block border-2 border-black px-4 py-2 rotate-[4deg] text-sm font-bold"
      >
        No. 001
      </div>

      <div class="text-center">
        <p
          class="text-[#A555EC] text-6xl md:text-8xl font-black uppercase tracking-tighter mb-6"
        >
          suspicious
        </p>

        <div class="mx-auto mb-8 h-1 w-32 bg-black"></div>

        <h1 class="text-3xl md:text-6xl font-black tracking-tight mb-6">
          Can you spot the fake?
        </h1>

        <p class="max-w-xl mx-auto text-neutral-700 text-base md:text-lg mb-10">
          Two images are placed under investigation. One is real. One was
          generated by AI. Your job is to pick the suspicious one.
        </p>

        <NuxtLink
          to="/play"
          class="inline-flex items-center justify-center border-2 border-black bg-black text-white px-9 py-4 font-bold uppercase shadow-[6px_6px_0px_#A555EC] hover:translate-x-1 hover:translate-y-1 hover:shadow-[3px_3px_0px_#A555EC] transition"
        >
          Open Case
        </NuxtLink>

        <div
          class="mt-10 max-w-sm mx-auto flex-col md:flex-row gap-2 md:gap-5 items-center text-sm text-neutral-600 border-t-2 border-black pt-5"
        >
          <NuxtTime
            :datetime="Date.now()"
            month="long"
            day="numeric"
            year="numeric"
          />

          <span class="hidden md:inline">•</span>

          <p>Image investigation game</p>
        </div>
      </div>
    </section>
  </main>
</template>
